/**
 * Grass Score — deterministic scoring engine (spec §16).
 *
 * A score from 0–1000 representing healthy real-world exploration.
 * NOT generated by an LLM. Fully transparent, stored with its components,
 * unit-tested, and gamed-resistant.
 *
 * Component budget:
 *   Outdoor duration       0–250   (full credit at 60 min outdoors)
 *   Pocket time            0–200   (full credit at 25 min away from the app)
 *   Mission completion     0–200   (50 per completed mission, cap 200)
 *   Observation diversity  0–150   (variety matters more than volume)
 *   Distance               0–100   (only when GPS permission exists)
 *   Discovery novelty      0–50    (10 per first-time category/tag)
 *   Streak                 0–50    (10 per consecutive exploration day, cap 5)
 *
 * Anti-gaming:
 *   - Pocket credit is scaled by the share of outdoor time actually spent away
 *     from the screen; sitting in the app does not earn pocket points.
 *   - Mission points cap out; you cannot farm 40 trivial missions.
 *   - Diversity needs both count AND variety (spamming one category is capped).
 *   - Distance is capped at 3 km and ignores GPS jitter below 100 m.
 *   - Skipped missions reduce mission credit proportionally.
 *   - GPS is never required: distance = 0 is a valid, honest zero.
 */
import type {
  Environment,
  GrassRank,
  GrassScoreComponents,
  GrassScoreInputs,
} from "@/lib/domain/types";
import { clamp } from "@/lib/utils";

export interface GrassScoreResult {
  score: number;
  rank: GrassRank;
  components: GrassScoreComponents;
  notes: string[];
  gpsAvailable: boolean;
}

export const GRASS_SCORE_MAX = 1000;

/** Component ceilings, in display order — one source for every breakdown UI. */
export const GRASS_COMPONENT_META: Array<{
  key: keyof GrassScoreComponents;
  label: string;
  max: number;
}> = [
  { key: "outdoorDuration", label: "Outdoor duration", max: 250 },
  { key: "pocketTime", label: "Phone-away time", max: 200 },
  { key: "missionCompletion", label: "Missions completed", max: 200 },
  { key: "observationDiversity", label: "Observation variety", max: 150 },
  { key: "distance", label: "Distance walked", max: 100 },
  { key: "discoveryNovelty", label: "New discoveries", max: 50 },
  { key: "streak", label: "Streak bonus", max: 50 },
];

const RANK_THRESHOLDS: Array<{ min: number; rank: GrassRank }> = [
  { min: 880, rank: "wildmind" },
  { min: 700, rank: "naturalist" },
  { min: 500, rank: "trailblazer" },
  { min: 300, rank: "explorer" },
  { min: 150, rank: "sprout" },
  { min: 0, rank: "seedling" },
];

export function grassRankFor(score: number): GrassRank {
  const s = clamp(score, 0, GRASS_SCORE_MAX);
  return RANK_THRESHOLDS.find((t) => s >= t.min)?.rank ?? "seedling";
}

export const GRASS_RANK_META: Record<GrassRank, { label: string; plant: string; blurb: string }> = {
  seedling: {
    label: "Seedling",
    plant: "🌱",
    blurb: "Every explorer starts here. Step outside and the score follows.",
  },
  sprout: {
    label: "Sprout",
    plant: "🌿",
    blurb: "You're finding your rhythm outdoors.",
  },
  explorer: {
    label: "Explorer",
    plant: "🥾",
    blurb: "Curiosity is becoming a habit.",
  },
  trailblazer: {
    label: "Trailblazer",
    plant: "🧭",
    blurb: "The world is your notebook now.",
  },
  naturalist: {
    label: "Naturalist",
    plant: "🦉",
    blurb: "You notice what most people walk past.",
  },
  wildmind: {
    label: "Wildmind",
    plant: "🏔️",
    blurb: "You belong outside. The screen is just a tool.",
  },
};

/** Deterministic per-component computation — exported so it is directly testable. */
export function computeComponents(input: GrassScoreInputs): GrassScoreComponents {
  // --- Outdoor duration: full at 60 minutes ---------------------------------
  const outdoorDuration = 250 * clamp(input.outdoorSeconds / 3600, 0, 1);

  // --- Pocket time: scaled by genuine away-share ----------------------------
  const awayShare =
    input.pocketSeconds + input.screenActiveSeconds <= 0
      ? 0
      : input.pocketSeconds / (input.pocketSeconds + input.screenActiveSeconds);
  const pocketBase = 200 * clamp(input.pocketSeconds / 1500, 0, 1);
  // In-app scrolling still earns progress, but at a fraction of the value.
  const pocketShare = 0.25 + 0.75 * clamp(awayShare, 0, 1);
  const pocketTime = pocketBase * pocketShare;

  // --- Mission completion: 50 each, less when missions were skipped ----------
  const attemptTotal = input.missionsCompleted + input.missionsSkipped;
  const skipDrag =
    attemptTotal === 0 ? 1 : clamp(input.missionsCompleted / Math.max(1, attemptTotal), 0.4, 1);
  const missionCompletion = clamp(input.missionsCompleted * 50, 0, 200) * skipDrag;

  // --- Observation diversity: variety-first ----------------------------------
  const categoryComponent = 60 * clamp(input.uniqueCategories / 5, 0, 1);
  const countComponent = 40 * clamp(input.observationCount / 8, 0, 1);
  const tagComponent = 50 * clamp(input.uniqueTags / 10, 0, 1);
  const observationDiversity = categoryComponent + countComponent + tagComponent;

  // --- Distance: honest zero without GPS -------------------------------------
  const usableDistance =
    input.distanceMeters !== null && input.distanceMeters >= 100 ? input.distanceMeters : 0;
  const distance = 100 * clamp(usableDistance / 3000, 0, 1);

  // --- Discovery novelty ------------------------------------------------------
  const discoveryNovelty = clamp(input.newDiscoveries * 10, 0, 50);

  // --- Streak ----------------------------------------------------------------
  const streak = clamp(input.streakDays * 10, 0, 50);

  return {
    outdoorDuration: round1(outdoorDuration),
    pocketTime: round1(pocketTime),
    missionCompletion: round1(missionCompletion),
    observationDiversity: round1(observationDiversity),
    distance: round1(distance),
    discoveryNovelty: round1(discoveryNovelty),
    streak: round1(streak),
  };
}

export function computeGrassScore(input: GrassScoreInputs): GrassScoreResult {
  const components = computeComponents(input);
  const raw = Object.values(components).reduce((a, b) => a + b, 0);
  const score = Math.round(clamp(raw, 0, GRASS_SCORE_MAX));
  const notes: string[] = [];

  if (input.distanceMeters === null) {
    notes.push("GPS off — distance contributes 0. Your score is still complete without it.");
  } else if (input.distanceMeters > 0 && input.distanceMeters < 100) {
    notes.push("Distance under 100 m ignored (GPS jitter guard).");
  }
  if (input.pocketSeconds === 0 && input.outdoorSeconds > 0) {
    notes.push(
      "No pocket time recorded yet — put the phone away during the expedition to earn up to 200 points."
    );
  }
  if (input.screenActiveSeconds > input.pocketSeconds && input.screenActiveSeconds > 300) {
    notes.push("Screen-active time exceeded pocket time — the outdoors pays better than the app.");
  }
  if (input.interruptionHeavy) {
    notes.push("Frequent app-switching detected — pocket credit reduced accordingly.");
  }
  if (input.missionsCompleted >= 3) {
    notes.push(
      "Mission completion hit its 200-point ceiling. Extra missions still count for discovery."
    );
  }

  return {
    score,
    rank: grassRankFor(score),
    components,
    notes,
    gpsAvailable: input.distanceMeters !== null,
  };
}

/**
 * Streak length from a set of date keys (YYYY-MM-DD), inclusive of today.
 * Deterministic; used by both the dashboard and the score engine.
 */
export function computeStreakDays(dateKeys: string[], todayKey: string): number {
  const unique = Array.from(new Set(dateKeys)).sort().reverse();
  if (unique.length === 0) return 0;
  const today = new Date(`${todayKey}T00:00:00`);
  let streak = 0;
  const cursor = new Date(today);
  // A streak may start today or yesterday (today's expedition not done yet).
  if (unique[0] !== todayKey) {
    cursor.setDate(cursor.getDate() - 1);
    const yesterdayKey = toKey(cursor);
    if (unique[0] !== yesterdayKey) return 0;
  }
  const set = new Set(unique);
  for (;;) {
    const key = toKey(cursor);
    if (set.has(key)) {
      streak += 1;
      cursor.setDate(cursor.getDate() - 1);
    } else {
      break;
    }
  }
  return streak;
}

function toKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function round1(n: number): number {
  return Math.round(n * 10) / 10;
}

/** Convenience builder with sane zero defaults — used by tests and the UI. */
export function grassInputs(partial: Partial<GrassScoreInputs>): GrassScoreInputs {
  return {
    outdoorSeconds: 0,
    pocketSeconds: 0,
    screenActiveSeconds: 0,
    distanceMeters: null,
    missionsCompleted: 0,
    missionsSkipped: 0,
    observationCount: 0,
    uniqueCategories: 0,
    uniqueTags: 0,
    newDiscoveries: 0,
    streakDays: 0,
    environment: "unknown" as Environment,
    interruptionHeavy: false,
    ...partial,
  };
}
