"use client";

/**
 * Landing-page Grass Score playground (spec §36, section 5).
 * Runs the REAL deterministic engine from src/lib/scoring — the same
 * function that scores expeditions — so the visual never over-promises.
 */
import * as React from "react";
import {
  GRASS_COMPONENT_META,
  GRASS_RANK_META,
  grassInputs,
  computeGrassScore,
} from "@/lib/scoring/grass-score";
import { cn } from "@/lib/utils";

interface SliderSpec {
  id: string;
  label: string;
  unit: string;
  min: number;
  max: number;
  defaultValue: number;
}

const SLIDERS: SliderSpec[] = [
  { id: "outside", label: "Time outdoors", unit: "min", min: 0, max: 90, defaultValue: 42 },
  {
    id: "screen",
    label: "Time looking at the screen",
    unit: "min",
    min: 0,
    max: 60,
    defaultValue: 8,
  },
  { id: "missions", label: "Missions completed", unit: "", min: 0, max: 5, defaultValue: 3 },
  { id: "observations", label: "Observations logged", unit: "", min: 0, max: 10, defaultValue: 6 },
];

export function GrassScoreDemo() {
  const [values, setValues] = React.useState<Record<string, number>>(() =>
    Object.fromEntries(SLIDERS.map((s) => [s.id, s.defaultValue]))
  );

  const result = React.useMemo(() => {
    const outdoorSeconds = values.outside * 60;
    const screenActiveSeconds = Math.min(values.screen * 60, outdoorSeconds);
    const pocketSeconds = Math.max(0, outdoorSeconds - screenActiveSeconds);
    const observations = values.observations;
    return computeGrassScore(
      grassInputs({
        outdoorSeconds,
        screenActiveSeconds,
        pocketSeconds,
        missionsCompleted: values.missions,
        missionsSkipped: 0,
        observationCount: observations,
        uniqueCategories: Math.min(observations, 5),
        uniqueTags: Math.min(observations * 2, 10),
        newDiscoveries: observations >= 4 ? 3 : observations >= 2 ? 1 : 0,
        streakDays: 3,
      })
    );
  }, [values]);

  const rank = GRASS_RANK_META[result.rank];

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_1.1fr] lg:gap-10">
      <div className="space-y-5">
        {SLIDERS.map((slider) => (
          <div key={slider.id}>
            <div className="flex items-baseline justify-between gap-3">
              <label htmlFor={`gs-${slider.id}`} className="text-sm font-medium">
                {slider.label}
              </label>
              <span className="font-display text-sm font-semibold tabular-nums text-forest">
                {values[slider.id]}
                {slider.unit ? ` ${slider.unit}` : ""}
              </span>
            </div>
            <input
              id={`gs-${slider.id}`}
              type="range"
              min={slider.min}
              max={slider.max}
              step={1}
              value={values[slider.id]}
              onChange={(event) =>
                setValues((prev) => ({ ...prev, [slider.id]: Number(event.target.value) }))
              }
              className="mt-2 h-2 w-full cursor-pointer appearance-none rounded-full bg-secondary accent-[hsl(var(--forest))]"
            />
          </div>
        ))}
        <p className="text-pretty text-xs text-muted-foreground">
          This is the real scoring engine — deterministic, transparent, and not generated by an AI
          model. GPS stays off; distance simply contributes zero.
        </p>
      </div>

      <div className="card-strata p-5 sm:p-6" aria-live="polite">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Grass Score
            </p>
            <p className="mt-1 font-display text-5xl font-semibold tabular-nums text-forest">
              {result.score}
              <span className="text-lg text-muted-foreground"> / 1000</span>
            </p>
          </div>
          <div className="text-right">
            <span className="text-4xl" aria-hidden>
              {rank.plant}
            </span>
            <p className="mt-1 text-sm font-semibold">{rank.label}</p>
          </div>
        </div>
        <p className="mt-1 text-pretty text-sm text-muted-foreground">{rank.blurb}</p>

        <div className="mt-5 space-y-3">
          {GRASS_COMPONENT_META.map((meta) => {
            const value = result.components[meta.key];
            const pct = Math.round((value / meta.max) * 100);
            return (
              <div key={meta.key}>
                <div className="flex items-baseline justify-between gap-3 text-xs">
                  <span className="text-muted-foreground">{meta.label}</span>
                  <span className="tabular-nums text-foreground/80">
                    {value} / {meta.max}
                  </span>
                </div>
                <div
                  className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"
                  role="img"
                  aria-label={`${meta.label}: ${value} of ${meta.max} points`}
                >
                  <div
                    className={cn(
                      "h-full rounded-full bg-forest/70 transition-[width] duration-300",
                      pct >= 80 && "bg-forest"
                    )}
                    style={{ width: `${Math.max(2, pct)}%` }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
