"use client";

/**
 * Grass Score — the deterministic measure of time well spent outside.
 * Every number here comes from stored scores; nothing is estimated on screen.
 */
import * as React from "react";
import { Award, Info, Medal, TrendingUp } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ScoreRing } from "@/components/score-ring";
import { PageHeader } from "@/components/layout/app-shell";
import {
  expeditionRepository,
  grassScoreRepository,
  missionRepository,
  observationRepository,
} from "@/lib/db/repositories";
import { earnedBadgeCount, evaluateBadges } from "@/lib/achievements/engine";
import type { BadgeStatus } from "@/lib/achievements/engine";
import { ForecastCard } from "@/features/score/forecast-card";
import {
  computeStreakDays,
  grassRankFor,
  GRASS_COMPONENT_META,
  GRASS_RANK_META,
} from "@/lib/scoring/grass-score";
import { cn, dateKey } from "@/lib/utils";
import type { GrassScore } from "@/lib/domain/types";

interface ScoreData {
  scores: GrassScore[];
  bestToday: GrassScore | null;
  personalBest: number;
  streakDays: number;
  badges: BadgeStatus[];
}

async function loadScores(): Promise<ScoreData> {
  const today = dateKey();
  const [all, expeditions, missions, observations] = await Promise.all([
    grassScoreRepository.all(),
    expeditionRepository.all(),
    missionRepository.all(),
    observationRepository.all(),
  ]);
  const todayScores = all.filter((s) => s.dateKey === today);
  const bestToday =
    todayScores.find((s) => s.scope === "day") ??
    todayScores.reduce<GrassScore | null>(
      (best, s) => (best === null || s.score > best.score ? s : best),
      null
    );
  const uniqueDays = Array.from(new Set(all.map((s) => s.dateKey)));
  return {
    scores: all,
    bestToday,
    personalBest: all.reduce((best, s) => Math.max(best, s.score), 0),
    streakDays: computeStreakDays(uniqueDays, today),
    badges: evaluateBadges({
      expeditions,
      missions,
      observations,
      scores: all,
      todayKey: today,
    }),
  };
}

/** Last 7 local days, with the best stored score for each. */
function lastSevenDays(
  scores: GrassScore[]
): Array<{ dayKey: string; label: string; best: number | null }> {
  const byDay = new Map<string, number>();
  for (const s of scores) {
    byDay.set(s.dateKey, Math.max(byDay.get(s.dateKey) ?? 0, s.score));
  }
  const days: Array<{ dayKey: string; label: string; best: number | null }> = [];
  for (let i = 6; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const key = dateKey(d);
    days.push({
      dayKey: key,
      label: d.toLocaleDateString(undefined, { weekday: "narrow" }),
      best: byDay.get(key) ?? null,
    });
  }
  return days;
}

export default function ScorePage() {
  const [data, setData] = React.useState<ScoreData | null>(null);

  React.useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const next = await loadScores();
        if (!cancelled) setData(next);
      } catch {
        if (!cancelled)
          setData({ scores: [], bestToday: null, personalBest: 0, streakDays: 0, badges: [] });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (data === null) {
    return (
      <div>
        <PageHeader title="Grass Score" description="How much of your life happened outside." />
        <Skeleton className="h-56 w-full" />
      </div>
    );
  }

  const week = lastSevenDays(data.scores);
  const today = data.bestToday;
  const sortedBadges = [...data.badges].sort((a, b) =>
    a.earned === b.earned ? b.progress / b.target - a.progress / a.target : a.earned ? -1 : 1
  );

  return (
    <div className="animate-fade-up space-y-5">
      <PageHeader
        title="Grass Score"
        description="Computed from behaviour, never generated by AI — a score you can explain."
      />

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base">Today</CardTitle>
          <CardDescription>
            {today
              ? `${GRASS_RANK_META[today.rank].plant} ${GRASS_RANK_META[today.rank].label} — ${GRASS_RANK_META[today.rank].blurb}`
              : "No expedition finished yet today."}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-5 sm:flex-row sm:items-start">
          <ScoreRing score={today?.score ?? 0} label={today ? "today" : "not yet"} />
          <div className="w-full flex-1 space-y-2.5">
            {GRASS_COMPONENT_META.map(({ key, label, max }) => {
              const value = today?.components[key] ?? 0;
              const pct = Math.round((value / max) * 100);
              return (
                <div key={key}>
                  <div className="mb-1 flex items-baseline justify-between text-xs">
                    <span className="text-muted-foreground">{label}</span>
                    <span className="tabular-nums">
                      {Math.round(value)}
                      <span className="text-muted-foreground">/{max}</span>
                    </span>
                  </div>
                  <div className="h-1.5 overflow-hidden rounded-full bg-muted" role="presentation">
                    <div
                      className="h-full rounded-full bg-forest transition-[width] duration-700"
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
        {today && today.notes.length > 0 ? (
          <CardContent className="pt-0">
            <details className="group">
              <summary className="flex cursor-pointer items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground">
                <Info className="h-3.5 w-3.5" aria-hidden />
                Why these numbers
              </summary>
              <ul className="mt-2 space-y-1 pl-5 text-xs text-muted-foreground">
                {today.notes.map((note) => (
                  <li key={note} className="list-disc text-pretty">
                    {note}
                  </li>
                ))}
              </ul>
            </details>
          </CardContent>
        ) : null}
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <TrendingUp className="h-4 w-4 text-forest" aria-hidden />
            Last 7 days
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex h-32 items-end justify-between gap-2" aria-hidden>
            {week.map(({ dayKey, label, best }) => {
              const height = best === null ? 4 : Math.max(6, Math.round((best / 1000) * 100));
              const isToday = dayKey === dateKey();
              return (
                <div key={dayKey} className="flex flex-1 flex-col items-center gap-1.5">
                  <div
                    className={`w-full max-w-9 rounded-t-md ${
                      best === null ? "bg-muted" : isToday ? "bg-forest" : "bg-forest/45"
                    }`}
                    style={{ height: `${height}%` }}
                    title={best === null ? "No score" : String(best)}
                  />
                  <span
                    className={`text-[10px] uppercase ${
                      isToday ? "font-semibold text-forest" : "text-muted-foreground"
                    }`}
                  >
                    {label}
                  </span>
                </div>
              );
            })}
          </div>
          <table className="sr-only">
            <caption>Best Grass Score per day, last 7 days</caption>
            <tbody>
              {week.map(({ dayKey, best }) => (
                <tr key={dayKey}>
                  <th scope="row">{dayKey}</th>
                  <td>{best === null ? "no score" : best}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>

      <ForecastCard />

      <div className="grid grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Award className="h-4 w-4 text-sunlight" aria-hidden />
              Personal best
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="font-display text-3xl font-semibold tabular-nums">{data.personalBest}</p>
            <p className="mt-1 text-xs text-muted-foreground">
              {GRASS_RANK_META[grassRankFor(data.personalBest)].label} tier
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Streak</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="font-display text-3xl font-semibold tabular-nums">{data.streakDays}</p>
            <p className="mt-1 text-xs text-muted-foreground">
              {data.streakDays === 1 ? "day in a row" : "days in a row"}
            </p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <Medal className="h-4 w-4 text-sunlight" aria-hidden />
            Badges
          </CardTitle>
          <CardDescription>
            {earnedBadgeCount(data.badges)} of {data.badges.length} earned — awarded from your
            stored field record, never from the network.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="grid grid-cols-3 gap-2.5 sm:grid-cols-4 md:grid-cols-6">
            {sortedBadges.map((badge) => (
              <li
                key={badge.id}
                title={badge.description}
                className={cn(
                  "rounded-xl border p-3 text-center",
                  badge.earned
                    ? "border-sunlight/50 bg-sunlight/10"
                    : "border-border/60 bg-muted/30"
                )}
              >
                <span
                  className={cn("text-xl", !badge.earned && "opacity-40 grayscale")}
                  aria-hidden
                >
                  {badge.emoji}
                </span>
                <p className="mt-1 truncate text-[11px] font-medium">{badge.label}</p>
                <p className="text-[10px] tabular-nums text-muted-foreground">
                  {badge.earned ? "Earned" : `${badge.progress}/${badge.target}`}
                </p>
                <span className="sr-only">
                  {badge.description} — {badge.earned ? "earned" : "not earned yet"}
                </span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <p className="text-pretty text-center text-xs text-muted-foreground">
        The Grass Score rewards presence, not perfection. Ten honest minutes outside beat an hour of
        scrolling about it.
      </p>
    </div>
  );
}
